language: python
python:
    - "2.7"
# Comandos para instalar las dependencias
notifications:
    email:
        recipients:
            - mamisho.mamisho@gmail.com
        on_success: always
        on_failure: always
install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install radon
    - pip install pep8
    - pip install mockito
# Comandos para ejecutar los test
script:
    - py.test --cov . --cov-report term-missing
after_success:
    - radon raw ./src/.
    - radon raw ./test/.
    - radon cc ./src/.
    - radon cc ./test/.
    - radon mi ./src/.
    - radon mi ./test/.
    - pep8 --statistics -qq ./src
    - pep8 --statistics -qq ./test
    - coveralls